#manual run 1
language: minimal
env:
  - CONST1: 5
script:
  - env
  - echo "alabala" 
  - if [ "$TRAVIS_PULL_REQUEST" ]; then echo alabala
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo my false; else echo not my mistake; fi
